name: imagenet=50
root: ~/datasets/ILSVRC2012
train:
  split: train
  manual_classes_fp: config/datasets/sub_imagenet_50.csv
val:
  split: val
  manual_classes_fp: config/datasets/sub_imagenet_50.csv
resize: 224
