dataset:
  name: imagenet
  root: ~/datasets/ILSVRC2012
  train:
    split: train
    make_partial: 0.01
  val:
    split: val
  resize: 224

training:
  train_epochs: 240
  print_interval: 20
  val_interval: 1000
  batch_size: 64
  num_workers: 16
  sync_bn: False
  pre_train: ~/model-zoo/hub/checkpoints/resnet50-19c8e357.pth

model:
  # cfg names
  name: official_models
  model_name: ResNet50

plot:
  direction:
    norm: filter
    ignore: bias_bn
  coordinate:
    x_axis:
      start: -1
      end: 1
      steps: 21
    y_axis:
      start: -1
      end: 1
      steps: 21
  cfg:
    levels: 5
    vtp_cfg:
      z_err_max: -1
      z_loss_max: 1.0e+9
      normalize_loss: -1
      num_interpolate_points: -1
      show_points: True
      show_polys: True

loss:
  name: ce_loss
  weight_dict:
    cls: 1.0
